FROM node:boron

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app


# Bundle app source
COPY . /usr/src/app
# Install app dependencies
COPY package_demo1.json /usr/src/app/package.json
RUN npm install

EXPOSE 3000

CMD [ "npm", "start" ]