FROM node:boron

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Bundle app source
COPY . /usr/src/app
RUN npm install
COPY package_emit.json /usr/src/app/package.json

EXPOSE 3000

CMD [ "npm", "start" ]